/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-sd:src/main/java/project/repository/Repository.e.vm.java
 */
package com.bia.todo.repository;

import com.bia.todo.domain.Product;
import com.bia.todo.repository.support.CustomRepository;

import java.util.List;


/**
 * Advanced CRUD Repository for {@link Product}.
 */
public interface ProductRepository extends CustomRepository<Product, String> {
    
    Product findByNameLower(String name);
    
    List<String> searchByName(String name);
}