/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-sd:src/main/java/project/repository/Repository.e.vm.java
 */
package com.bia.todo.repository;

//import com.bia.productecategory.domain.Category;

import com.bia.todo.domain.Category;
import com.bia.todo.repository.support.CustomRepository;

//import com.bia.todo.repository.support.CustomRepository;

/**
 * Advanced CRUD Repository for {@link Category}.
 */
public interface CategoryRepository extends CustomRepository<Category, String> {
}