/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-sd:src/test/java/repository/RepositoryWithRealSessionTest.e.vm.java
 */
package com.bia.todo.repository;

import static org.fest.assertions.Assertions.assertThat;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.apache.log4j.Logger;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.google.common.collect.Sets;

import com.bia.todo.domain.Users;
import com.bia.todo.repository.UsersGenerator;
import com.bia.todo.repository.UsersRepository;

/**
 * Integration test on {@link UsersRepository}
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class UsersRepositoryWithRealSessionTest {
    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(UsersRepositoryWithRealSessionTest.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Autowired
    private UsersRepository usersRepository;

    @Autowired
    private UsersGenerator usersGenerator;

    @Test
    public void identityShouldBePreserved() {
        Users users = usersGenerator.getUsers();

        // add it to a Set before saving (force equals/hashcode)
        Sets.newHashSet(users);

        usersRepository.save(users);
        entityManager.flush();

        // reload it from cache and check equality
        Integer id = users.getId();
        assertThat(users).isEqualTo(usersRepository.findOne(id));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(users.getId()).isEqualTo(usersRepository.findOne(id).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(users).isNotEqualTo(usersRepository.findOne(id));
    }
}