/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-sd:src/test/java/repository/ModelGenerator.e.vm.java
 */
package com.bia.todo.repository;

import org.springframework.stereotype.Service;
import com.bia.todo.domain.Item;
import com.bia.todo.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Service
public class ItemGenerator {

    /**
     * Returns a new Item instance filled with random values.
     */
    public Item getItem() {
        Item item = new Item();

        // simple attributes follows
        item.setName("a");
        item.setTag("a");
        item.setDue(true);
        item.setFrequency(1);
        item.setMonthDay(1);
        return item;
    }

}